import db from './db';
import { createOrGetCarrierEnquiry } from './enquiry-manager';
import { dispatchOutboundWebhooks } from './webhook-dispatcher';

export interface WorkflowCondition {
  field: string; // e.g. 'carrierCode', 'declaredValue', 'breachHours', 'destinationCountry'
  operator: 'EQUALS' | 'NOT_EQUALS' | 'GREATER_THAN' | 'LESS_THAN' | 'CONTAINS';
  value: string | number;
}

export interface WorkflowAction {
  type:
    | 'CREATE_ENQUIRY_DRAFT'
    | 'AUTO_SEND_ENQUIRY'
    | 'DISPATCH_WEBHOOK'
    | 'SET_INVESTIGATION_STATUS'
    | 'APPLY_TAG';
  parameters: Record<string, unknown>;
}

export interface WorkflowEvaluationContext {
  organizationId: string;
  parcelId: string;
  trackingNumber: string;
  carrierCode: string;
  trackingStatus: string;
  isBreached: boolean;
  breachHours: number;
  stalledHours: number;
  declaredValue: number;
  destinationCountry: string;
}

/**
 * Checks if a parcel context satisfies all conditions of a workflow rule
 */
export function evaluateCondition(condition: WorkflowCondition, context: WorkflowEvaluationContext): boolean {
  const target = (context as unknown as Record<string, unknown>)[condition.field];
  if (target === undefined || target === null) return false;

  switch (condition.operator) {
    case 'EQUALS':
      return String(target).toLowerCase() === String(condition.value).toLowerCase();
    case 'NOT_EQUALS':
      return String(target).toLowerCase() !== String(condition.value).toLowerCase();
    case 'GREATER_THAN':
      return Number(target) > Number(condition.value);
    case 'LESS_THAN':
      return Number(target) < Number(condition.value);
    case 'CONTAINS':
      return String(target).toLowerCase().includes(String(condition.value).toLowerCase());
    default:
      return false;
  }
}

/**
 * Executes safe sandboxed actions for a triggered workflow rule
 */
export async function executeWorkflowAction(
  action: WorkflowAction,
  context: WorkflowEvaluationContext
): Promise<{ actionType: string; success: boolean; details?: unknown }> {
  const { organizationId, parcelId } = context;

  switch (action.type) {
    case 'CREATE_ENQUIRY_DRAFT': {
      const res = await createOrGetCarrierEnquiry({
        organizationId,
        parcelId,
        sendingMode: 'STAFF_APPROVAL',
        enquiryType: 'SLA_BREACH',
        notes: 'Automatically generated by workflow rule.',
      });
      return { actionType: action.type, success: true, details: res };
    }
    case 'AUTO_SEND_ENQUIRY': {
      const res = await createOrGetCarrierEnquiry({
        organizationId,
        parcelId,
        sendingMode: 'AUTO_SEND',
        enquiryType: 'SLA_BREACH',
        notes: 'Dispatched immediately by auto-send workflow rule.',
      });
      return { actionType: action.type, success: true, details: res };
    }
    case 'DISPATCH_WEBHOOK': {
      const res = await dispatchOutboundWebhooks({
        organizationId,
        eventType: 'parcel.workflow_triggered',
        payload: {
          parcelId,
          trackingNumber: context.trackingNumber,
          carrier: context.carrierCode,
          status: context.trackingStatus,
          timestamp: new Date().toISOString(),
        },
      });
      return { actionType: action.type, success: true, details: res };
    }
    case 'SET_INVESTIGATION_STATUS': {
      const newStatus = String(action.parameters.status || 'OPEN');
      await db.parcel.update({
        where: { id: parcelId },
        data: { investigationStatus: newStatus },
      });
      return { actionType: action.type, success: true, details: { newStatus } };
    }
    case 'APPLY_TAG': {
      const tag = String(action.parameters.tag || 'FLAGGED');
      const parcel = await db.parcel.findUnique({ where: { id: parcelId } });
      if (parcel) {
        const customValues = JSON.parse(parcel.customFieldValues || '{}');
        customValues.workflow_tag = tag;
        await db.parcel.update({
          where: { id: parcelId },
          data: { customFieldValues: JSON.stringify(customValues) },
        });
      }
      return { actionType: action.type, success: true, details: { tag } };
    }
    default:
      return { actionType: action.type, success: false, details: 'Unknown safe action' };
  }
}

/**
 * Triggers all active workflows for an event type (e.g. SLA_BREACHED, TRACKING_STATUS_CHANGED)
 */
export async function triggerWorkflowsForParcel(
  triggerEvent: string,
  context: WorkflowEvaluationContext
): Promise<{ executedRulesCount: number; actionResults: unknown[] }> {
  const rules = await db.workflowRule.findMany({
    where: {
      organizationId: context.organizationId,
      triggerEvent,
      isActive: true,
    },
  });

  const actionResults: unknown[] = [];
  let executedRulesCount = 0;

  for (const rule of rules) {
    const conditions = JSON.parse(rule.conditions || '[]') as WorkflowCondition[];
    const actions = JSON.parse(rule.actions || '[]') as WorkflowAction[];

    const matchesAll = conditions.every((cond) => evaluateCondition(cond, context));
    if (matchesAll) {
      for (const act of actions) {
        const res = await executeWorkflowAction(act, context);
        actionResults.push({ ruleName: rule.name, ...res });
      }
      executedRulesCount++;
    }
  }

  return { executedRulesCount, actionResults };
}

/**
 * Saves a new workflow rule with automated version snapshotting
 */
export async function saveWorkflowRuleWithVersion(params: {
  organizationId: string;
  ruleId?: string;
  name: string;
  description?: string;
  triggerEvent: string;
  conditions: WorkflowCondition[];
  actions: WorkflowAction[];
  requiresApproval?: boolean;
  userId?: string;
  changeNotes?: string;
}) {
  const {
    organizationId,
    ruleId,
    name,
    description,
    triggerEvent,
    conditions,
    actions,
    requiresApproval = false,
    userId,
    changeNotes,
  } = params;

  const conditionsJson = JSON.stringify(conditions);
  const actionsJson = JSON.stringify(actions);

  let rule;
  let newVersionNumber = 1;

  if (ruleId) {
    const existing = await db.workflowRule.findFirst({
      where: { id: ruleId, organizationId },
    });
    if (!existing) throw new Error('Workflow rule not found');

    newVersionNumber = existing.version + 1;
    rule = await db.workflowRule.update({
      where: { id: ruleId },
      data: {
        name,
        description,
        triggerEvent,
        conditions: conditionsJson,
        actions: actionsJson,
        requiresApproval,
        version: newVersionNumber,
        updatedAt: new Date(),
      },
    });
  } else {
    rule = await db.workflowRule.create({
      data: {
        organizationId,
        name,
        description,
        triggerEvent,
        conditions: conditionsJson,
        actions: actionsJson,
        requiresApproval,
        version: 1,
        createdById: userId || null,
      },
    });
  }

  // Create immutable version snapshot
  await db.workflowVersion.create({
    data: {
      organizationId,
      workflowRuleId: rule.id,
      versionNumber: newVersionNumber,
      snapshot: JSON.stringify({ name, description, triggerEvent, conditions, actions, requiresApproval }),
      changeNotes: changeNotes || `Updated to version ${newVersionNumber}`,
      createdById: userId || null,
    },
  });

  return rule;
}

/**
 * Rolls back a workflow rule to an earlier version snapshot
 */
export async function rollbackWorkflowRule(
  organizationId: string,
  ruleId: string,
  targetVersionNumber: number,
  userId?: string
) {
  const targetSnapshot = await db.workflowVersion.findFirst({
    where: {
      organizationId,
      workflowRuleId: ruleId,
      versionNumber: targetVersionNumber,
    },
  });

  if (!targetSnapshot) {
    throw new Error(`Target version snapshot ${targetVersionNumber} not found.`);
  }

  const parsed = JSON.parse(targetSnapshot.snapshot);
  const currentRule = await db.workflowRule.findFirst({
    where: { id: ruleId, organizationId },
  });

  if (!currentRule) throw new Error('Rule not found');

  const newVersionNumber = currentRule.version + 1;

  const updatedRule = await db.workflowRule.update({
    where: { id: ruleId },
    data: {
      name: parsed.name,
      description: parsed.description,
      triggerEvent: parsed.triggerEvent,
      conditions: JSON.stringify(parsed.conditions),
      actions: JSON.stringify(parsed.actions),
      requiresApproval: parsed.requiresApproval || false,
      version: newVersionNumber,
      updatedAt: new Date(),
    },
  });

  // Record rollback version
  await db.workflowVersion.create({
    data: {
      organizationId,
      workflowRuleId: ruleId,
      versionNumber: newVersionNumber,
      snapshot: targetSnapshot.snapshot,
      changeNotes: `Rolled back to Version ${targetVersionNumber}`,
      createdById: userId || null,
    },
  });

  await db.auditLog.create({
    data: {
      organizationId,
      userId: userId || null,
      action: 'WORKFLOW_ROLLEDBACK',
      entityType: 'WORKFLOW',
      entityId: ruleId,
      details: JSON.stringify({ restoredVersion: targetVersionNumber, newVersion: newVersionNumber }),
    },
  });

  return updatedRule;
}
